baseURL = "/"
languageCode = "en-us"
title = "Linode CMS"

[outputs]
  page = ["json"]
  home = ["json", "redirect"]
  section = ["json"]
  taxonomy = ["json", "changelog"]

[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

[outputFormats.events]
  baseName = "events"
  mediatype = "application/json"

[outputFormats.changelogs]
  baseName = "changelogs"
  mediatype = "application/json"

[outputFormats.redirect]
  mediatype = "text/netlify"
  baseName = "_redirects"

[taxonomies]
  sites = "sites"
  changelog = "changelog"

[permalinks]
  page = "/:section/:title/"