baseURL = "/"
languageCode = "en-us"
title = "Linode CMS"

[outputs]
  page = ["json"]
  home = ["json", "redirect"]
  teams = ["json"]
  section = ["json"]
  taxonomy = ["json"]

[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

[outputFormats.events]
  baseName = "events"
  mediatype = "application/json"

[outputFormats.redirect]
  mediatype = "text/netlify"
  baseName = "_redirects"

[taxonomies]
  sport = "sports"
  practice = "practices"

[permalinks]
  page = "/:section/:title/"