backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:

  - name: "events" # Used in routes, e.g., /admin/collections/blog

    label: "Event" # Used in the UI

    folder: "content/events" # The path to the folder where the documents are stored

    create: true # Allow users to create new documents in this collection

    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: true
        widget: "datetime"
        default: ""

      - label: "Start Date"
        name: "start_date"
        required: true
        widget: "datetime"
        default: ""

      - label: "End Date"
        name: "end_date"
        required: true
        widget: "datetime"
        default: ""

      - label: "Location"
        name: location
        widget: "string"
        required: true

      - label: "Event URL"
        name: "event_url"
        widget: "string"
        required: true

      - label: "Sites"
        name: "sites"
        required: false
        widget: list
        hint: "Select a site for this event to appear (other than the marketing site)"
        field: {
          label: "Site",
          name: "site",
          widget: "select",
          options: ["developers"]
        }

      - label: "Image"
        name: "image_url"
        required: false
        widget: "image"

      - label: "Content"
        name: "body"
        widget: "markdown"
        required: false
  
  - name: "changelog" # Used in routes, e.g., /admin/collections/blog

    label: "Changelogs" # Used in the UI

    folder: "content/changelog" # The path to the folder where the documents are stored

    create: true # Allow users to create new documents in this collection

    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: true
        widget: "datetime"
        default: ""

      - label: "Changelog Type"
        name: "changelog"
        required: true
        widget: list
        field: {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["API", "Cloud Manager"]
        }

      - label: "Content"
        name: "body"
        widget: "markdown"
        required: true